ModelName: t1_best_2b
Backend: Vitis
OutputDir: outputs/t1/2bits
ProjectName: t1_best_2b
KerasH5: models/results/t1/2bits/best/model.h5
InputData: data/hls/t1/2bits/input_features.dat
OutputPredictions: data/hls/t1/2bits/output_predictions.dat
Part: xc7z020clg400-1
ClockPeriod: 10
IOType: io_stream
HLSConfig:
  Model:
    Precision:
      default: ap_fixed<8,1>
    ReuseFactor: 1
    Strategy: Latency
    BramFactor: 1000000000
    TraceOutput: false
  LayerName:
    input_3:
      Trace: true
      Precision:
        result: auto
    q_conv2d_4:
      Trace: true
      Precision:
        result: auto
        weight: fixed<2,2,TRN,WRAP,0>
        bias: fixed<2,2,TRN,WRAP,0>
    q_conv2d_4_linear:
      Trace: true
      Precision:
        result: auto
    batch_normalization_6:
      Trace: true
      Precision:
        result: auto
        scale: auto
        bias: auto
    q_activation_6:
      Trace: true
      Precision:
        result: int<2>
    q_conv2d_5:
      Trace: true
      Precision:
        result: auto
        weight: fixed<2,2,TRN,WRAP,0>
        bias: fixed<2,2,TRN,WRAP,0>
    q_conv2d_5_linear:
      Trace: true
      Precision:
        result: auto
    batch_normalization_7:
      Trace: true
      Precision:
        result: auto
        scale: auto
        bias: auto
    q_activation_7:
      Trace: true
      Precision:
        result: int<2>
    flatten_2:
      Trace: true
      Precision:
        result: auto
    q_dense_4:
      Trace: true
      Precision:
        result: auto
        weight: fixed<2,2,TRN,WRAP,0>
        bias: fixed<2,2,TRN,WRAP,0>
    q_dense_4_linear:
      Trace: true
      Precision:
        result: auto
    batch_normalization_8:
      Trace: true
      Precision:
        result: auto
        scale: auto
        bias: auto
    q_activation_8:
      Trace: true
      Precision:
        result: int<2>
    q_dense_5:
      Trace: true
      Precision:
        result: auto
        weight: fixed<2,2,TRN,WRAP,0>
        bias: fixed<2,2,TRN,WRAP,0>
    q_dense_5_softmax:
      Trace: true
      Precision:
        result: auto
