ModelName: t1_best_2b
Backend: Vitis
OutputDir: outputs/t1/2bits
ProjectName: t1_best_2b
KerasH5: models/results/t1/2bits/best/model.h5
InputData: data/hls/t1/2bits/input_features.dat
OutputPredictions: data/hls/t1/2bits/output_predictions.dat
Part: xc7z020clg400-1
ClockPeriod: 10
IOType: io_stream
HLSConfig:
  Model:
    Strategy: Latency
    ReuseFactor: 1
    Precision:
      default: ap_uint<2>
      weight: ap_uint<2>
      bias: ap_uint<2>
      result: ap_uint<2>
      accum: ap_uint<4>
  LayerType:
    Conv2D:
      Strategy: Latency
      ReuseFactor: 1
      Precision:
        weight: ap_uint<2>
        bias: ap_uint<2>
        result: ap_uint<2>
        accum: ap_uint<4>
    Dense:
      Strategy: Latency
      ReuseFactor: 1
      Precision:
        weight: ap_uint<2>
        bias: ap_uint<2>
        result: ap_uint<2>
        accum: ap_uint<4>
  LayerName:
    q_conv2d_8:
      Trace: true
    batch_normalization_12:
      Trace: true
    q_activation_12:
      Trace: true
    q_conv2d_9:
      Trace: true
    batch_normalization_13:
      Trace: true
    q_activation_13:
      Trace: true
    flatten_4:
      Trace: true
    q_dense_8:
      Trace: true
    batch_normalization_14:
      Trace: true
    q_activation_14:
      Trace: true
    q_dense_9:
      Trace: true
